= Erdoğan CİVİL

== Ortaklar;
1. Hasan ÇÖDEK -130201066
2. İbrahim Aykut KÖSE 130201046
3. Ali ŞENLİKÇİ 120201047
4. Zeynep ÇELİK 110201070

Adres:https://github.com/120201047/Proje

== Projede Yaptıklarım


. Splash Screen
. Web Servis 


=== 1)Splash Screen

1. Uygulama başlarken gösterilen logo, tanıtım gibi aktivitedir.

[source , java  ]
-----
public class SplashActivity extends Activity {


    private static int SPLASH_TIME_OUT = 1000;    <1>
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        startHandler();

    }
    public void startHandler(){

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {

                intetLogin  =new Intent(getApplicationContext(),Login.class);
                 startActivity(intetLogin);

                finish();
            }
        }, SPLASH_TIME_OUT);
    }

}
-----


=== 2)Web Servis

2. Web Servis web üzerinden HTTP protokolü ile hizmet veren program parçalarıdır. 

Ben web servis'i php olarak yazdım. Aşağıda bu kodlar ve ne işe yaradıkları basitçe belirtilmiştir.

[source , php  ]
-----
<?php
define("DB_HOST", "localhost");
define("DB_USER", "bitirme");
define("DB_PASSWORD", "4b3giTb60M");
define("DB_NAME", "bitirme_kullanicilar");
class DbConnect{
	
	private $connect;
	
	public function __construct(){
		
		$this->connect = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		 
		if (mysqli_connect_errno($this->connect))
		{
			echo "Failed to connect to MySQL: " . mysqli_connect_error();  
		}
	}
	
	public function getDb(){
		
		return $this->connect;
	}
	
}
-----

Yukarıdaki kod parçası veritabanı bağlantısını sağlar. Bağlantı olmaması durumunda hata verir.


[source , php  ]
-----
<?php
require_once 'include/user.php';
$username = "";
$password = "";
$email = "";
if(isset($_POST['kAdi'])){
$kAdi = $_POST['kAdi'];
}
if(isset($_POST['sifre'])){
$sifre = $_POST['sifre'];
}
if(isset($_POST['email'])){
$email = $_POST['email'];
}
// Instance of a User class
$userObject = new User();
// Registration of new user
if(!empty($kAdi) && !empty($sifre) && !empty($email)){
$hashed_sifre = md5($sifre);
$json_registration = $userObject->createNewRegisterUser($kAdi, $hashed_sifre, $email);
echo json_encode($json_registration);
}
// User Login
if(!empty($kAdi) && !empty($sifre) && empty($email)){
$hashed_sifre = md5($sifre);
$json_array = $userObject->loginUsers($kAdi, $hashed_sifre);
echo json_encode($json_array);
}
?>
-----

Yukarıdaki kod parçası değişken tanımlamalarının kontrolünü yapar. Ve kullanıcı parolasının şifrelendiği kısmı içeririr.

[source , php  ]
-----
<?php
include_once 'db.php';
class User{
	
	private $db;
	private $db_table = "kullanici";
	
	public function __construct(){
		$this->db = new DbConnect();
	}
	
	public function isLoginExist($kAdi, $sifre){		
				
		$query = "select * from " . $this->db_table . " where kAdi = '$kAdi' AND sifre = '$sifre' Limit 1";
		$result = mysqli_query($this->db->getDb(), $query);
		if(mysqli_num_rows($result) > 0){
			mysqli_close($this->db->getDb());
			return true;
		}		
		mysqli_close($this->db->getDb());
		return false;		
	}
	
	public function createNewRegisterUser($kAdi, $sifre, $email){
			
		$query = "insert into kullanici ( kAdi, sifre, email, kayit_tarihi) values ('$kAdi', '$sifre', '$email', NOW())";
		$inserted = mysqli_query($this->db->getDb(), $query);
		if($inserted == 1){
			$json['success'] = 1;									
		}else{
			$json['success'] = 0;
		}
		mysqli_close($this->db->getDb());
		return $json;
	}
	
	public function loginUsers($kAdi, $sifre){
			
		$json = array();
		$canUserLogin = $this->isLoginExist($kAdi, $sifre);
		if($canUserLogin){
			$json['success'] = 1;
		}else{
			$json['success'] = 0;
		}
		return $json;
	}
}
?>
-----

Yukarıdaki kod parçası da kullanıcıya ait bilgilerin kontrol edildiği, yeni kullanıcı kaydı oluşrulduğu kısımları içerir.
