= Zeynep ÇELİK

== Projede Yaptıklarım


. Android LifeCycle
   
   Projede oluşturduğum Finish butonu ile projenin yaşam döngüsünü oluşturdum.
   Toast komutut-ylada ekrana yazdırma işlemini gerçekleştirdim.
   

=== 



[source , java  ]
-----

     textView = (TextView) findViewById(R.id.textView2);
      String msg = "Instructions: \n "
                 "0. New instance (onCreate, onStart, onResume) \n "
                  "1. Back Arrow (onPause, onStop, onDestroy) \n "
                  "2. Finish (onPause, onStop, onDestroy) \n "
                 "3. Home (onPause, onStop) \n ";
         textView.setText(msg);
         button = (Button) findViewById(R.id.button1);
 button.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
                 finish();
             }
         });
         Toast.makeText(getApplicationContext(), "onCreate", 1).show();
     }
     @Override
     protected void onPause() {
         super.onPause();
         Toast.makeText(this, "onPause", 1).show();
     }
     @Override
     protected void onRestart() {
         super.onRestart();
        Toast.makeText(this, "onRestart", 1).show();
     }
     @Override
     protected void onResume() {
         super.onResume();
         Toast.makeText(this, "onResume", 1).show();
     }
     @Override
     protected void onStart() {
         super.onStart();
         Toast.makeText(this, "onStart", 1).show();
     }
     @Override
     protected void onDestroy() {
         super.onDestroy();
         Toast.makeText(this, "onDestroy", 1).show();
     }
     @Override
     protected void onStop() {
         super.onStop();
         Toast.makeText(this, "onStop", 1).show();
      }
      @Override
      public boolean onCreateOptionsMenu(Menu menu) {
       @@ private int returnParsedJsonObject(String result){
          return returnedResult;
      }
  }
